"""add card_bonus_categories

Revision ID: 0fe120ef4019
Revises: 2eb9a2617bbf
Create Date: 2026-02-18 15:38:07.464146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe120ef4019'
down_revision: Union[str, None] = '2eb9a2617bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_bonus_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('multiplier', sa.String(length=50), nullable=False),
    sa.Column('portal_only', sa.Boolean(), nullable=False),
    sa.Column('cap', sa.Integer(), nullable=True),
    sa.Column('from_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_bonus_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_bonus_categories_card_id'), ['card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_bonus_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_bonus_categories_card_id'))

    op.drop_table('card_bonus_categories')
    # ### end Alembic commands ###
