"""initial schema

Revision ID: 8abde7989620
Revises: 
Create Date: 2026-02-17 17:03:21.552207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abde7989620'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('issuer_url', sa.String(length=500), nullable=True),
    sa.Column('authorization_url', sa.String(length=500), nullable=True),
    sa.Column('token_url', sa.String(length=500), nullable=True),
    sa.Column('userinfo_url', sa.String(length=500), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_user')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_setting')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=False)

    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=200), nullable=True),
    sa.Column('template_version_id', sa.String(length=200), nullable=True),
    sa.Column('card_image', sa.String(length=200), nullable=True),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('last_digits', sa.String(length=5), nullable=True),
    sa.Column('issuer', sa.String(length=100), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('annual_fee', sa.Integer(), nullable=True),
    sa.Column('annual_fee_date', sa.Date(), nullable=True),
    sa.Column('annual_fee_user_modified', sa.Boolean(), nullable=False),
    sa.Column('credit_limit', sa.Integer(), nullable=True),
    sa.Column('custom_notes', sa.Text(), nullable=True),
    sa.Column('custom_tags', sa.JSON(), nullable=True),
    sa.Column('spend_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('spend_requirement', sa.Integer(), nullable=True),
    sa.Column('spend_deadline', sa.Date(), nullable=True),
    sa.Column('spend_reminder_notes', sa.Text(), nullable=True),
    sa.Column('signup_bonus_amount', sa.Integer(), nullable=True),
    sa.Column('signup_bonus_type', sa.String(length=100), nullable=True),
    sa.Column('signup_bonus_earned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_status'), ['status'], unique=False)

    op.create_table('card_benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('benefit_name', sa.String(length=200), nullable=False),
    sa.Column('benefit_amount', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('reset_type', sa.String(length=20), nullable=False),
    sa.Column('from_template', sa.Boolean(), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('amount_used', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('benefit_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_benefits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_benefits_card_id'), ['card_id'], unique=False)

    op.create_table('card_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_events_card_id'), ['card_id'], unique=False)

    op.create_table('card_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('bonus_source', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('bonus_amount', sa.Integer(), nullable=True),
    sa.Column('bonus_credit_amount', sa.Integer(), nullable=True),
    sa.Column('bonus_type', sa.String(length=100), nullable=True),
    sa.Column('bonus_earned', sa.Boolean(), nullable=False),
    sa.Column('bonus_missed', sa.Boolean(), nullable=False),
    sa.Column('spend_requirement', sa.Integer(), nullable=True),
    sa.Column('spend_deadline', sa.Date(), nullable=True),
    sa.Column('spend_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('spend_reminder_notes', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['card_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_bonuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_bonuses_card_id'), ['card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_bonuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_bonuses_card_id'))

    op.drop_table('card_bonuses')
    with op.batch_alter_table('card_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_events_card_id'))

    op.drop_table('card_events')
    with op.batch_alter_table('card_benefits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_benefits_card_id'))

    op.drop_table('card_benefits')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_status'))
        batch_op.drop_index(batch_op.f('ix_cards_profile_id'))

    op.drop_table('cards')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_user_id'))

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_table('settings')
    op.drop_table('oauth_states')
    op.drop_table('oauth_providers')
    # ### end Alembic commands ###
